[package]
name = "duckity_rs"
version = "0.1.3"
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "duckity_rs"
crate-type = ["cdylib"]

[dependencies]
duckity = "1.0.3"
pyo3 = { version = "0.27.0" }
